// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7QWA2YXPE-eemax2CJhN3dYdjJm-HyE',
    appId: '1:897840345231:web:ecb1ff692ce26963bc80fa',
    messagingSenderId: '897840345231',
    projectId: 'beautify-bd62c',
    authDomain: 'beautify-bd62c.firebaseapp.com',
    storageBucket: 'beautify-bd62c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-cOD_o_rTaugKXI9qDnrHpXgbPP2ojCc',
    appId: '1:897840345231:android:b2e13b56eea5a492bc80fa',
    messagingSenderId: '897840345231',
    projectId: 'beautify-bd62c',
    storageBucket: 'beautify-bd62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzsw9fvVlOzrbbff96HCsM4DVwa-gYWVo',
    appId: '1:897840345231:ios:2ba95c9ef7e2ab6bbc80fa',
    messagingSenderId: '897840345231',
    projectId: 'beautify-bd62c',
    storageBucket: 'beautify-bd62c.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzsw9fvVlOzrbbff96HCsM4DVwa-gYWVo',
    appId: '1:897840345231:ios:2ba95c9ef7e2ab6bbc80fa',
    messagingSenderId: '897840345231',
    projectId: 'beautify-bd62c',
    storageBucket: 'beautify-bd62c.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH7QWA2YXPE-eemax2CJhN3dYdjJm-HyE',
    appId: '1:897840345231:web:13f3d22b15465163bc80fa',
    messagingSenderId: '897840345231',
    projectId: 'beautify-bd62c',
    authDomain: 'beautify-bd62c.firebaseapp.com',
    storageBucket: 'beautify-bd62c.appspot.com',
  );
}
